# -*- coding: utf-8 -*-
"""RAG-ResumeAnalyser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whvoMUVAzfk8KjSp48zusBV4TzXj1yf4
"""

!pip install chromadb sentence-transformers groq

!pip install pypdf

from sentence_transformers import SentenceTransformer
import chromadb
import groq

groq.api_key="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"

from google.colab import files
from pypdf import PdfReader

uploaded = files.upload()

documents = []

for pdf_file in uploaded.keys():
    reader = PdfReader(pdf_file)

    text = ""
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"

    documents.append(text)

print(f"Extracted {len(documents)} resumes")

# The following lines caused an IndexError because only one document was uploaded.
# If you intend to upload multiple files, please do so when prompted.
# Otherwise, access documents[0] for the first document.
# documents[0]  # Resume 1 text
# documents[1]  # Resume 2 text
# documents[2]  # Resume 3 text

# Display the first extracted document if available
if documents:
    print("\nContent of the first extracted document:")
    print(documents[0][:500]) # Print first 500 characters of the first document

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
doc_embeddings=model.encode(documents).astype("float32")

doc_embeddings.shape

def chunk_text(text, chunk_size=500):
    chunks = []

    for i in range(0, len(text), chunk_size):
        chunks.append(text[i:i+chunk_size])

    return chunks

import chromadb
from sentence_transformers import SentenceTransformer

# Embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Chroma client
client = chromadb.Client()

collection = client.create_collection("resume_rag")

doc_id = 0

for doc in documents:

    chunks = chunk_text(doc["text"])

    embeddings = embedding_model.encode(chunks).tolist()

    collection.add(
        documents=chunks,
        embeddings=embeddings,
        ids=[str(doc_id+i) for i in range(len(chunks))],
        metadatas=[{"resume": doc["name"]} for _ in chunks]
    )

    doc_id += len(chunks)

print("Stored in ChromaDB")

from groq import Groq

GROQ_API_KEY="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"

groq_client = Groq(
    api_key=GROQ_API_KEY
)

def ask_resume_bot(query):

    # Create query embedding
    query_embedding = embedding_model.encode(query).tolist()

    # Retrieve top chunks
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=3
    )

    retrieved_chunks = results["documents"][0]

    context = "\n\n".join(retrieved_chunks)

    prompt = f"""
You are a resume assistant.

Answer only from the context below.

Context:
{context}

Question:
{query}

Answer:
"""

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role":"user","content":prompt}
        ],
        temperature=0
    )

    return response.choices[0].message.content

while True:

    question = input("Ask Question: ")

    if question.lower() == "exit":
        break

    elif "compare" in question.lower():
        print(compare_candidates())

    else:
        print(ask_resume_bot(question))